Development
tenantcloud/ansible-role-vault-server pull request #1
Opened 2020-06-04 11:59 UTC by odebretseni

2020-06-04 14:37 UTC, BrunIF requested changes

2020-06-04 14:37 UTC, BrunIF commented on meta/main.yml
> +  role_name: vault
`vault` or `vault_server` ?

2020-06-04 14:37 UTC, BrunIF commented on meta/main.yml
> +  issue_tracker_url: https://github.com/tenantcloud/ansible-role-vault/issues
https://github.com/tenantcloud/ansible-role-vault-server/issues

2020-06-04 14:37 UTC, BrunIF commented on tasks/configure-vault.yml
> +  command: systemctl start vault.service
Use `systemd` module https://docs.ansible.com/ansible/latest/modules/systemd_module.html

2020-06-04 14:37 UTC, BrunIF commented on tasks/configure-vault.yml
> +  command: systemctl enable vault.service
also

2020-06-04 14:37 UTC, BrunIF commented on tasks/configure-vault.yml
> +  shell: "echo 'vault_root_token: {{ vault_root_token }}' >> /etc/{{ vault_work_dir }}/vault_root_token.txt"
better
```copy: content="{{ your_json_feed }}" dest=/path/to/destination/file```
or
```local_action: copy content="{{ foo_result.stdout }}" dest="/path/to/destination/file"```

2020-06-04 14:37 UTC, BrunIF commented on tasks/configure-vault.yml
> +    url: "https://{{ vault_domain }}:8200"
create variable 
`vault_url`
vault_url: "https://{{ vault_domain }}:8200"

simple and better

2020-06-04 14:37 UTC, BrunIF commented on templates/vault.service.j2
> +[Unit]
Тут нічого не перезаписується. Це файл.

2020-06-04 20:07 UTC, odebretseni commented on tasks/configure-vault.yml
> +  command: systemctl start vault.service
одне з питань що я казав - чомусь модуль не відпрацьовує

2020-06-04 20:07 UTC, odebretseni commented on tasks/configure-vault.yml
> +  command: systemctl enable vault.service
аналогічно

2020-06-04 20:08 UTC, odebretseni commented on templates/vault.service.j2
> +[Unit]
я трішки поправив - там вже є змінна також

2020-06-09 07:43 UTC, BrunIF approved these changes

2020-06-09 07:43 UTC, merged